import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { refonteColors as c } from '@klaim/shared';
import { useSession } from '../src/lib/session';
import { screen } from '../src/lib/analytics';
import { useSocialEpoch2026, socialRpc2026, useSocialRead2026 } from '../src/features/social/social2026Data';
import { socialError2026, type SocialPerson2026 } from '../src/features/social/social2026Model';
import { parseSocialGraph } from '../src/features/social/socialGraph';
import { SocialAvatar2026 } from '../src/features/social/SocialPostCard2026';
import { ProfileLink, ProfilePage, ProfileSection, s, useRefonteCopy } from '../src/features/refonte/ProfilePrimitives';
import { AccountDoor2026 } from '../src/features/account/AccountDoor2026';
export default function FriendsRoute(){const {session}=useSession();const epoch=useSocialEpoch2026();return <Friends key={epoch+':'+(session?.user.id??'guest')}/>;}
function Friends(){const copy=useRefonteCopy();const graphRead=useSocialRead2026<unknown>('social_graph');const blocked=useSocialRead2026<{id:string;name:string|null}[]>('social_block_list_2026');const graph=parseSocialGraph(graphRead.data);const [query,setQuery]=useState('');const [search,setSearch]=useState('');const people=useSocialRead2026<SocialPerson2026[]>('social_people_2026',{p_query:search});const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{screen('amis')},[]);useEffect(()=>{const timer=setTimeout(()=>setSearch(query.trim()),250);return()=>clearTimeout(timer)},[query]);
 async function respond(request:string,accept:boolean){if(!graphRead.owner||busy)return;setBusy(true);setError(null);try{const result=await socialRpc2026<{ok:boolean;reason?:string}>(graphRead.owner,'friend_respond',{p_request_id:request,p_accept:accept});if(!result.ok)throw new Error(result.reason);graphRead.reload()}catch(e){setError(socialError2026(String(e),copy('fr','en')==='en'))}finally{setBusy(false)}}
 return <ProfilePage title={copy('Amis','Friends')} back>
 {graphRead.status==='signedOut'?<AccountDoor2026 reason={copy('Retrouve tes partenaires de sortie. Ton compte porte la recherche de membres et tes demandes d’amis.','Find your activity partners. Your account carries member search and your friend requests.')}/>:<>
 <TextInput accessibilityLabel={copy('Rechercher un membre','Search members')} placeholder={copy('Nom ou pseudo','Name or handle')} placeholderTextColor={c.darkMuted} style={s.input} value={query} onChangeText={setQuery} autoCapitalize="none" autoCorrect={false}/>
 {search.length>=2?people.status==='loading'?<ActivityIndicator color={c.darkInk}/>:people.status==='failed'?<ProfileLink title={copy('Réessayer la recherche','Retry search')} icon="scout" onPress={people.reload}/>:people.data?.length?people.data.map(person=><Pressable accessibilityRole="button" key={person.id} style={{flexDirection:'row',alignItems:'center',gap:12,minHeight:70}} onPress={()=>router.push({pathname:'/member',params:{userId:person.id}})}><SocialAvatar2026 person={person}/><View><Text style={s.linkTitle}>{person.name}</Text><Text style={s.meta}>@{person.handle}</Text></View></Pressable>):<Text style={[s.meta,{marginVertical:18}]}>{copy('Aucun profil accessible pour cette recherche.','No accessible profiles match your search.')}</Text>:<Text style={[s.meta,{marginVertical:14}]}>{copy('Les profils privés ne sont pas affichés.','Private profiles are not shown.')}</Text>}
 {graphRead.status==='loading'?<ActivityIndicator color={c.darkInk}/>:graphRead.status==='failed'||!graph?<><Text style={s.body}>{copy('Les relations n’ont pas pu être lues.','Relationships could not be loaded.')}</Text><ProfileLink title={copy('Réessayer','Retry')} icon="historique" onPress={graphRead.reload}/></>:<>
 {graph.requestsIn.length?<><ProfileSection title={copy('Demandes reçues','Requests')}/>{graph.requestsIn.map(person=><View key={person.id} style={{paddingVertical:12}}><Text style={s.linkTitle}>{person.displayName??person.handle}</Text><View style={{flexDirection:'row',gap:20}}><Pressable accessibilityRole="button" disabled={busy} style={{minHeight:44,justifyContent:'center'}} onPress={()=>void respond(person.id,true)}><Text style={s.body}>{copy('Accepter','Accept')}</Text></Pressable><Pressable accessibilityRole="button" disabled={busy} style={{minHeight:44,justifyContent:'center'}} onPress={()=>void respond(person.id,false)}><Text style={s.meta}>{copy('Refuser','Decline')}</Text></Pressable></View></View>)}</>:null}
 <ProfileSection title={copy('Mes amis','My friends')}/>{graph.friends.length?graph.friends.map(person=><ProfileLink key={person.handle} title={person.displayName??person.handle??copy('Profil privé','Private profile')} icon="ami" onPress={()=>router.push({pathname:'/member',params:{handle:person.handle??''}})}/>):<Text style={s.meta}>{copy('Retrouve un membre avec son nom ou son pseudo.','Find a member by name or handle.')}</Text>}
 {graph.following.length?<><ProfileSection title={copy('Abonnements','Following')}/>{graph.following.map(person=><ProfileLink key={person.handle} title={person.displayName??person.handle??copy('Profil privé','Private profile')} icon="ami" onPress={()=>router.push({pathname:'/member',params:{handle:person.handle??''}})}/>)}</>:null}
 </>}
 {blocked.data?.length?<><ProfileSection title={copy('Membres bloqués','Blocked members')}/>{blocked.data.map(person=><ProfileLink key={person.id} title={person.name??copy('Membre bloqué','Blocked member')} subtitle={copy('Débloquer','Unblock')} icon="verrou" onPress={()=>{if(blocked.owner)void socialRpc2026(blocked.owner,'social_block_2026',{p_user_id:person.id,p_blocked:false}).then(()=>{blocked.reload();graphRead.reload()}).catch(e=>setError(socialError2026(String(e),copy('fr','en')==='en')))}}/>)}</>:null}
 {error?<Text accessibilityRole="alert" style={s.body}>{error}</Text>:null}<ProfileLink title={copy('Mon profil','My profile')} icon="profil" onPress={()=>router.push('/profil-edit')}/>
 </>}
 </ProfilePage>;
}
