import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import * as Crypto from 'expo-crypto';
import { refonteColors as c } from '@klaim/shared';
import { useSession } from '../src/lib/session';
import { screen } from '../src/lib/analytics';
import { useSocialEpoch2026, socialRpc2026, useSocialRead2026 } from '../src/features/social/social2026Data';
import { socialError2026, type SocialPost2026, type SocialComment2026 } from '../src/features/social/social2026Model';
import { SocialPostCard2026 } from '../src/features/social/SocialPostCard2026';
import { ProfileButton, ProfileLink, ProfilePage, ProfileSection, ProfileSegments, lightStyles, s as darkStyles, useRefonteCopy } from '../src/features/refonte/ProfilePrimitives';
const s = { ...darkStyles, ...lightStyles };
export default function FeedRoute(){const {session}=useSession();const epoch=useSocialEpoch2026();return <Feed key={epoch+':'+(session?.user.id??'guest')}/>;}
function Feed(){
 const copy=useRefonteCopy();const params=useLocalSearchParams<{activity?:string;postId?:string}>();const [activity,setActivity]=useState<'run'|'bike'>(params.activity==='bike'?'bike':'run');
 const feed=useSocialRead2026<SocialPost2026[]>('social_feed_2026',{p_activity:activity,p_post_id:params.postId??null});const comments=useSocialRead2026<SocialComment2026[]>('social_comments_read_2026',{p_post_id:params.postId??null});
 const [body,setBody]=useState('');const [commentId,setCommentId]=useState(()=>Crypto.randomUUID());const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);const [confirm,setConfirm]=useState<{post?:string;comment?:string;report?:boolean}|null>(null);
 useEffect(()=>{screen('crew_feed')},[]);
 async function mutate(rpc:string,args:Record<string,unknown>,success?:()=>void){if(lock.current||!feed.owner)return;lock.current=true;setBusy(true);setError(null);try{await socialRpc2026(feed.owner,rpc,args);success?.();feed.reload();comments.reload()}catch(e){setError(socialError2026(String(e),copy('fr','en')==='en'))}finally{lock.current=false;setBusy(false)}}
 const detail=params.postId?feed.data?.[0]:null;
 return <ProfilePage tone="light" title={params.postId?copy('Publication','Post'):copy('Le fil du crew','Crew feed')} back backHref="/(tabs)/crew">
 {!params.postId?<ProfileSegments tone="light" value={activity} onChange={setActivity} options={[{key:'run',label:copy('Course','Run')},{key:'bike',label:copy('Vélo','Ride')}]}/>:null}
 {feed.status==='signedOut'?<><Text style={[s.body,{marginBottom:20}]}>{copy('Les photos et récits de sortie restent entre les membres du crew. Connecte-toi pour retrouver le fil.','Activity photos and stories stay within the crew. Sign in to view the feed.')}</Text><View style={{alignSelf:'flex-start'}}><ProfileButton tone="light" label={copy('Connexion','Sign in')} onPress={()=>router.push('/sign-in')}/></View></>:feed.status==='loading'?<ActivityIndicator color={c.ink}/>:feed.status==='failed'?<><Text style={s.body}>{copy('Le fil est indisponible.','Feed unavailable.')}</Text><ProfileButton tone="light" label={copy('Réessayer','Retry')} onPress={feed.reload}/></>:feed.data?.length?feed.data.map(post=><SocialPostCard2026 tone="light" key={post.id} post={post} busy={busy} onReact={()=>void mutate('social_react_2026',{p_post_id:post.id,p_reacted:!post.reacted})} onOpen={()=>router.push({pathname:'/crew-feed',params:{activity,postId:post.id}})}/>):<Text style={[s.body,{marginVertical:24}]}>{params.postId?copy('Cette publication n’est plus accessible.','This post is no longer accessible.'):copy('Les sorties partagées volontairement par ton crew apparaîtront ici.','Activities voluntarily shared by your crew will appear here.')}</Text>}
 {!params.postId ? <ProfileLink tone="light" title={copy('Conversation du crew','Crew conversation')} icon="crew" onPress={()=>router.push('/crew-conversation')}/> : null}
 {!params.postId?<ProfileLink tone="light" title={copy('Choisir une sortie dans mon journal','Choose an activity from my journal')} icon="historique" onPress={()=>router.push('/(tabs)/profil')}/>:detail?<>
 <ProfileSection tone="light" title={copy('Commentaires','Comments')}/>
 {comments.status==='failed'?<ProfileLink tone="light" title={copy('Recharger les commentaires','Reload comments')} icon="historique" onPress={comments.reload}/>:comments.data?.map(comment=><View key={comment.id} style={{paddingVertical:12,borderBottomWidth:1,borderColor:c.border}}><Pressable accessibilityRole="button" style={{minHeight:32}} onPress={()=>router.push({pathname:'/member',params:{userId:comment.author.id}})}><Text style={s.linkTitle}>{comment.author.name}</Text></Pressable><Text style={s.body}>{comment.body}</Text><Pressable accessibilityRole="button" style={{minHeight:44,justifyContent:'center'}} onPress={()=>setConfirm(comment.mine?{comment:comment.id}:{comment:comment.id,report:true})}><Text style={s.meta}>{comment.mine?copy('Retirer','Remove'):copy('Signaler','Report')}</Text></Pressable></View>)}
 <TextInput value={body} onChangeText={setBody} maxLength={400} multiline placeholder={copy('Ajouter un commentaire…','Add a comment…')} placeholderTextColor={c.muted} accessibilityLabel={copy('Commentaire','Comment')} style={[s.input,{marginTop:18,minHeight:80,textAlignVertical:'top'}]}/>
 <View style={{alignSelf:'flex-start',marginVertical:14}}><ProfileButton tone="light" label={copy('Envoyer','Send')} disabled={!body.trim()} busy={busy} onPress={()=>void mutate('social_comment_2026',{p_post_id:detail.id,p_client_id:commentId,p_body:body},()=>{setBody('');setCommentId(Crypto.randomUUID())})}/></View>
 <ProfileLink tone="light" title={detail.mine?copy('Retirer la publication','Remove post'):copy('Signaler la publication','Report post')} icon="alerte" onPress={()=>setConfirm(detail.mine?{post:detail.id}:{post:detail.id,report:true})}/>
 {!detail.mine?<ProfileLink tone="light" title={copy('Bloquer ce membre','Block member')} icon="verrou" onPress={()=>void mutate('social_block_2026',{p_user_id:detail.author.id,p_blocked:true},()=>setNotice(copy('Membre bloqué.','Member blocked.')))}/>:null}
 </>:null}
 {confirm?<View style={[s.gap,{paddingVertical:18}]}><Text style={s.body}>{confirm.report?copy('Le signalement sera transmis et ce contenu sera masqué pour toi.','The report will be submitted and this content hidden for you.'):copy('Retirer ce contenu du fil ? Ta sortie reste dans ton journal.','Remove this content from the feed? Your activity stays in your journal.')}</Text>{confirm.report?(['privacy','harassment','inappropriate','other'] as const).map(reason=><ProfileButton tone="light" key={reason} secondary label={reason==='privacy'?copy('Vie privée','Privacy'):reason==='harassment'?copy('Harcèlement','Harassment'):reason==='inappropriate'?copy('Contenu inapproprié','Inappropriate content'):copy('Autre motif','Other reason')} busy={busy} onPress={()=>void mutate('social_report_2026',{p_reason:reason,p_post_id:confirm.post??null,p_comment_id:confirm.comment??null},()=>{setConfirm(null);setNotice(copy('Signalement transmis.','Report submitted.'))})}/>):<ProfileButton tone="light" label={copy('Confirmer le retrait','Confirm removal')} secondary busy={busy} onPress={()=>void mutate('social_remove_2026',{p_post_id:confirm.post??null,p_comment_id:confirm.comment??null},()=>setConfirm(null))}/>}<ProfileButton tone="light" label={copy('Annuler','Cancel')} secondary onPress={()=>setConfirm(null)}/></View>:null}
 {error?<Text accessibilityRole="alert" style={s.body}>{error}</Text>:null}{notice?<Text accessibilityRole="alert" style={s.meta}>{notice}</Text>:null}
 </ProfilePage>;
}
