import { parseCommercialSnapshot2026 } from '../_shared/commercial2026.ts';
const assert=(v:unknown,message:string)=>{if(!v)throw Error(message);};
const config=[{id:'relief',entitlement_id:'test_relief',product_ids:['test.product.relief']}];
function payload(){return {request_date_ms:Date.parse('2026-09-09T12:00:00Z'),subscriber:{entitlements:{test_relief:{product_identifier:'test.product.relief',expires_date:null}},non_subscriptions:{'test.product.relief':[{purchase_date:'2026-09-01T00:00:00Z',is_sandbox:false,refunded_at:null as string|null}]}}};}
Deno.test('commercial RC: configured perpetual entitlement and its receipt required',()=>{const value=payload();assert(parseCommercialSnapshot2026(value,config,false)?.items[0]?.owned,'Real non-consumable grants');assert(parseCommercialSnapshot2026(value,[{...config[0],product_ids:['other']}],false)?.items[0]?.owned===false,'Wrong product cannot grant');});
Deno.test('commercial RC: subscription absence does not revoke a paid permanent collection',()=>{assert(parseCommercialSnapshot2026(payload(),config,false)?.items[0]?.owned,'No subscription in payload, collection still owned');});
Deno.test('commercial RC: removal of entitlement revokes access after refund or transfer',()=>{const value=payload();value.subscriber.entitlements={} as typeof value.subscriber.entitlements;assert(parseCommercialSnapshot2026(value,config,false)?.items[0]?.owned===false,'Removed entitlement cannot survive cached receipt');});
Deno.test('commercial RC: refunded receipts never grant even if entitlement remains',()=>{const value=payload();value.subscriber.non_subscriptions['test.product.relief'][0].refunded_at='2026-09-08T00:00:00Z';assert(parseCommercialSnapshot2026(value,config,false)?.items[0]?.owned===false,'Refund overrides apparent permanent entitlement');});
Deno.test('commercial RC: sandbox and unknown environment cannot grant production ownership',()=>{const value=payload();value.subscriber.non_subscriptions['test.product.relief'][0].is_sandbox=true;assert(!parseCommercialSnapshot2026(value,config,false)?.items[0]?.owned,'Production excludes sandbox');assert(parseCommercialSnapshot2026(value,config,true)?.items[0]?.owned,'Explicit test backend supports sandbox');delete (value.subscriber.non_subscriptions['test.product.relief'][0] as {is_sandbox?:boolean}).is_sandbox;assert(!parseCommercialSnapshot2026(value,config,true)?.items[0]?.owned,'Unknown environment denied');});
Deno.test('commercial RC: malformed snapshot is retriable and blank config invents no products',()=>{assert(parseCommercialSnapshot2026({},config,false)===null,'Malformed response fails');assert(parseCommercialSnapshot2026(payload(),[{id:'relief',entitlement_id:null,product_ids:[]}],false)?.items.length===0,'No invented Store configuration');});
