import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { randomUUID } from 'expo-crypto';
import { CHALLENGE_RULES_2026 as rules, fonts, refonteColors as c } from '@klaim/shared';
import { useSession } from '../../lib/session';
import { useLocale } from '../../i18n/store';
import { screen } from '../../lib/analytics';
import { GrydIcon } from '../../ui/gryd';
import { useRealCrew } from '../crew/real';
import { useCrewDiscovery } from '../crew/discoveryData';
import { useCrewChallenges2026, type CrewChallengeMutation2026 } from './useCrewChallenges2026';
import { challengeActions2026, nextChallengeStarts2026, type CrewChallenge2026 } from './CrewChallengesModel2026';
import { CrewArenaPreview2026 } from './CrewArenaPreview2026';
import { ProfileButton, ProfileLink, ProfilePage, ProfileSection, ProfileSegments, s, useRefonteCopy } from './ProfilePrimitives';

export function CrewChallenges2026Screen() {
  const { session, loading } = useSession();
  return <CrewChallengesContents2026 key={loading ? 'restoring' : session?.user.id ?? 'anonymous'} />;
}
function CrewChallengesContents2026() {
  const copy = useRefonteCopy(); const locale = useLocale(); const { configured } = useSession();
  const [activity, setActivity] = useState<'run' | 'bike'>('run'); const [mode, setMode] = useState<'list' | 'create' | 'detail'>('list');
  const [selectedId, setSelectedId] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [scoresExpanded, setScoresExpanded] = useState(false);
  const [confirm, setConfirm] = useState<'cancel' | 'withdraw' | { runId: string } | null>(null); const [consent, setConsent] = useState(false); const [accessConsent, setAccessConsent] = useState(false);
  const [query, setQuery] = useState(''); const [arenaId, setArenaId] = useState<string | null>(null); const [opponentId, setOpponentId] = useState<string | null>(null); const [startsAt, setStartsAt] = useState<string | null>(null); const [draftId, setDraftId] = useState(randomUUID);
  const crew = useRealCrew({ withOverview: true }); const data = useCrewChallenges2026(activity);
  const discovery = useCrewDiscovery({ cityId: crew.crew?.cityId ?? null, query });
  useEffect(() => { screen('crew-challenges'); }, []);
  const selected = data.matches.find(match => match.id === selectedId) ?? null;
  const arena = data.arenas.find(item => item.id === arenaId) ?? null;
  const dates = useMemo(() => arena ? nextChallengeStarts2026(Date.now(), arena.timeZone) : [], [arena]);
  const opponents = discovery.page?.crews.filter(item => item.id !== crew.crew?.id) ?? [];
  const opponent = opponents.find(item => item.id === opponentId);
  const direction = ['founder', 'co_captain'].includes(crew.overview?.myRole ?? '');
  const datetime = (value: string, timeZone: string) => new Date(value).toLocaleString(locale, { timeZone, weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
  const statusLabel = (match: CrewChallenge2026) => ({ invited: copy('Invitation', 'Invitation'), assembling: copy('Équipes en formation', 'Building teams'), scheduled: copy('Programmé', 'Scheduled'), active: Date.now() >= Date.parse(match.endsAt) ? copy('Dernières synchronisations', 'Final synchronizations') : copy('En cours', 'Active'), final: copy('Terminé', 'Final'), cancelled: copy('Annulé', 'Cancelled') })[match.status];
  const errorLabel = (reason: string) => {
    if (reason.includes('team_full')) return copy('Les cinq places de cette équipe sont prises.', 'All five places in this team are taken.');
    if (reason.includes('five_volunteers_required')) return copy('Il faut cinq volontaires encore membres du crew pour figer l’équipe.', 'Five volunteers who are still crew members are needed to lock the team.');
    if (reason.includes('roster_locked')) return copy('L’équipe est déjà figée. Aucune nouvelle inscription n’est possible.', 'The team is locked. New registrations are closed.');
    if (reason.includes('authentication_required')) return copy('Reconnecte-toi pour continuer.', 'Sign in again to continue.');
    if (reason.includes('direction_required')) return copy('Cette action est réservée à la direction du crew.', 'This action is reserved for crew leaders.');
    if (reason.includes('no_crew')) return copy('Il faut appartenir à un crew pour proposer un défi.', 'You need to belong to a crew to propose a challenge.');
    if (reason.includes('arena_unavailable')) return copy('Cette arène n’est plus publiée. Actualise la liste des arènes.', 'This arena is no longer published. Refresh the arena list.');
    if (reason.includes('challenge_started')) return copy('Le défi a commencé. Son annulation n’est plus possible.', 'The challenge has started and can no longer be cancelled.');
    if (reason.includes('preference_unavailable')) return copy('Ce choix de secteur n’est plus disponible.', 'This sector preference is no longer available.');
    if (reason.includes('challenge_closed')) return copy('Ce défi est clos : son résultat publié ne change plus. Une sortie précise peut encore être retirée dans « Mes journées ».', 'This challenge is closed: its published result no longer changes. A specific activity can still be withdrawn under “My days”.');
    if (reason.includes('challenge_unavailable')) return copy('Ce défi n’est plus disponible pour cette action. Actualise la liste.', 'This challenge is no longer available for this action. Refresh the list.');
    if (reason.includes('23505') || reason.includes('player_already_registered')) return copy('Une inscription existe déjà pour cette semaine et cette discipline.', 'A registration already exists for this week and sport.');
    return copy('L’action n’a pas abouti. Actualise puis réessaie.', 'The action did not complete. Refresh and try again.');
  };
  // Ce que la confirmation promet est ce que le serveur fait : un retrait global
  // efface TOUTES les journées comptées, un retrait d’activité une seule (0148).
  function confirmCopy(match: CrewChallenge2026, pending: 'cancel' | 'withdraw' | { runId: string }) {
    if (pending === 'cancel') return copy('Annuler ce défi pour les deux crews ? Les sorties enregistrées restent conservées.', 'Cancel this challenge for both crews? Recorded activities are kept.');
    if (typeof pending === 'object') return copy('Retirer cette sortie du défi ? Seule cette journée cesse de compter ; la tentative reste consommée et la sortie reste dans ton journal.', 'Withdraw this activity from the challenge? Only this day stops counting; the attempt stays consumed and the activity stays in your journal.');
    if (match.status !== 'cancelled' && Date.now() < Date.parse(match.startsAt)) return copy('Retirer ton inscription ? Ta place sera libérée et ton équipe devra être figée à nouveau.', 'Withdraw your registration? Your place will be released and your team must be locked again.');
    const counted = match.myContributions.filter(item => !item.withdrawn).length;
    if (counted === 0) return copy('Retirer ton consentement ? Aucune de tes prochaines sorties ne comptera dans ce défi. Tes sorties restent dans ton journal.', 'Withdraw your consent? None of your next activities will count in this challenge. Your activities stay in your journal.');
    return copy(`Retirer ton consentement retire TES ${counted} ${counted > 1 ? 'journées déjà comptées' : 'journée déjà comptée'} dans ce défi, pas une seule sortie. Les tentatives consommées ne reviennent pas et le score de ton équipe est recalculé. Tes sorties restent dans ton journal.`,
      `Withdrawing your consent removes ALL ${counted} counted ${counted > 1 ? 'days' : 'day'} in this challenge, not a single activity. Consumed attempts do not come back and your team score is recomputed. Your activities stay in your journal.`);
  }
  async function mutate(name: CrewChallengeMutation2026, args: Record<string, string | boolean>, success: string) {
    setNotice(null); const result = await data.mutate(name, args);
    if (!result.ok) { setNotice(errorLabel(result.reason)); return null; }
    setNotice(success); setConfirm(null); setConsent(false); setAccessConsent(false); return result.data;
  }
  function openMatch(match: CrewChallenge2026) { setSelectedId(match.id); setMode('detail'); setNotice(null); setConfirm(null); setConsent(false); setAccessConsent(false); setScoresExpanded(false); }
  function startCreate() { setMode('create'); setNotice(null); setDraftId(randomUUID()); setArenaId(null); setOpponentId(null); setStartsAt(null); setAccessConsent(false); }
  async function createMatch() {
    if (!arena || !opponent || !startsAt || !accessConsent || !direction) return;
    const response = await mutate('create_crew_challenge_2026', { p_client_id: draftId, p_opponent_crew_id: opponent.id, p_arena_id: arena.id, p_starts_at: startsAt, p_access_confirmed: true }, copy('Invitation créée. Chaque membre choisit ensuite de participer.', 'Invitation created. Each member then chooses whether to participate.'));
    if (response && typeof response === 'object' && typeof (response as { id?: unknown }).id === 'string') { setSelectedId((response as { id: string }).id); setMode('detail'); }
  }
  const checkbox = (checked: boolean, setChecked: (v: boolean) => void, label: string) => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked, disabled: data.busy }} disabled={data.busy} onPress={() => setChecked(!checked)} style={local.check}><View style={[local.checkBox, checked && local.checked]}>{checked ? <GrydIcon name="check" size={14} color={c.ink} /> : null}</View><Text style={[s.meta, { flex: 1 }]}>{label}</Text></Pressable>;
  const choice = (key: string, chosen: boolean, title: string, detail: string | null, onPress: () => void) => <Pressable key={key} accessibilityRole="radio" accessibilityState={{ selected: chosen, disabled: data.busy }} disabled={data.busy} onPress={onPress} style={[local.choice, chosen && local.chosen]}><View style={s.flex}><Text style={s.linkTitle}>{title}</Text>{detail ? <Text style={s.meta}>{detail}</Text> : null}</View><GrydIcon name={chosen ? 'check' : 'chevronRight'} size={18} color={chosen ? c.accent : c.darkMuted} /></Pressable>;

  return <ProfilePage title={copy('Défis crew', 'Crew challenges')} back backHref="/(tabs)/crew">
    <View style={local.heading}><View style={s.flex}><Text style={s.title}>{copy('5 contre 5', '5 versus 5')}</Text><Text style={s.meta}>{copy(`${rules.durationDays} jours · ${rules.sectorCount} secteurs · volontaires`, `${rules.durationDays} days · ${rules.sectorCount} sectors · voluntary`)}</Text></View><GrydIcon name="versus" size={28} color={c.darkInk} /></View>
    {mode !== 'list' ? <Pressable accessibilityRole="button" onPress={() => { setMode('list'); setNotice(null); setConfirm(null); }} style={local.back}><Text style={s.linkAction}>← {copy('Tous les défis', 'All challenges')}</Text></Pressable> : <ProfileSegments value={activity} onChange={value => { setActivity(value); setSelectedId(null); setNotice(null); }} options={[{ key: 'run', label: copy('Course', 'Run') }, { key: 'bike', label: copy('Vélo', 'Ride') }]} />}
    {notice ? <Text accessibilityRole="alert" style={[s.body, { marginVertical: 18 }]}>{notice}</Text> : null}
    {data.status === 'signed-out' ? <View style={s.state}><Text style={s.body}>{copy('Connecte-toi et rejoins un crew pour participer.', 'Sign in and join a crew to participate.')}</Text>{configured ? <ProfileButton label={copy('Me connecter', 'Sign in')} onPress={() => router.push('/sign-in')} /> : null}</View> : data.status === 'loading' ? <View style={s.state}><ActivityIndicator color={c.darkInk} /><Text style={s.meta}>{copy('Lecture des défis…', 'Loading challenges…')}</Text></View> : data.status !== 'ready' ? <View style={s.state}><Text style={s.body}>{copy('Les défis ne peuvent pas être chargés pour le moment.', 'Challenges cannot be loaded right now.')}</Text><ProfileButton label={copy('Réessayer', 'Try again')} onPress={data.reload} /></View> : mode === 'list' ? <>
      {data.matches.length ? <><ProfileSection title={copy('Défis de mon crew', 'My crew’s challenges')} />{data.matches.map(match => <Pressable accessibilityRole="button" key={match.id} onPress={() => openMatch(match)} style={local.match}><View style={local.matchTop}><Text style={local.label}>{statusLabel(match)}</Text><GrydIcon name="chevronRight" size={18} color={c.darkMuted} /></View><Text style={local.matchTitle}>{match.teams.map(team => team.name).join(' / ')}</Text><Text style={s.meta}>{match.title} · {datetime(match.startsAt, match.timeZone)}</Text><Text style={s.meta}>{match.joined ? copy('Tu participes', 'You are participating') : copy('Participation facultative', 'Participation is optional')}</Text></Pressable>)}</> : <View style={s.empty}><Text style={s.sectionTitle}>{copy('Aucun défi pour le moment', 'No challenges yet')}</Text><Text style={s.meta}>{copy('Les invitations reçues et les défis de ton crew apparaîtront ici.', 'Invitations and your crew’s challenges will appear here.')}</Text></View>}
      {data.arenas.length === 0 ? <View style={s.state}><Text style={s.body}>{copy('Aucune arène publiée pour cette discipline.', 'No arena published for this sport.')}</Text><Text style={s.meta}>{copy('Un défi pourra être créé lorsqu’une arène accessible et ses secteurs auront été publiés.', 'A challenge can be created once an accessible arena and its sectors have been published.')}</Text></View> : crew.loading ? <ActivityIndicator color={c.darkInk} /> : !crew.crew ? <ProfileButton label={copy('Rejoindre un crew', 'Join a crew')} onPress={() => router.push('/(tabs)/crew')} /> : direction ? <View style={{ marginTop: 22 }}><ProfileButton label={copy('Inviter un crew', 'Invite a crew')} icon="plus" onPress={startCreate} /></View> : <Text style={[s.meta, { marginTop: 18 }]}>{copy('La direction du crew peut proposer une rencontre. Chacun décide de s’inscrire.', 'Crew leaders can propose a match. Everyone chooses whether to join.')}</Text>}
      <ProfileLink title={copy('Actualiser les défis', 'Refresh challenges')} icon="historique" onPress={data.reload} />
    </> : mode === 'create' ? <>
      <ProfileSection title={copy('Une arène publiée', 'A published arena')} />
      {data.arenas.map(item => choice(item.id, item.id === arenaId, item.title, `${item.sectors.map(sector => sector.title).join(' · ')} · ${item.timeZone}`, () => { setArenaId(item.id); setStartsAt(null); setAccessConsent(false); setDraftId(randomUUID()); }))}
      {arena ? <><CrewArenaPreview2026 sectors={arena.sectors} /><Text style={s.meta}>{copy('Accès vérifié le ', 'Access reviewed on ')}{new Date(arena.reviewedAt).toLocaleDateString(locale)}</Text>{/^https?:\/\//i.test(arena.accessSource) ? <ProfileLink title={copy('Consulter la source d’accès', 'View access source')} icon="lien" onPress={() => { void Linking.openURL(arena.accessSource).catch(() => setNotice(copy('La source n’a pas pu être ouverte.', 'The source could not be opened.'))); }} /> : <Text style={s.meta}>{arena.accessSource}</Text>}</> : null}
      <ProfileSection title={copy('Le crew invité', 'The invited crew')} />
      <TextInput accessibilityLabel={copy('Rechercher un crew', 'Search crews')} placeholder={copy('Nom du crew', 'Crew name')} placeholderTextColor={c.darkMuted} value={query} onChangeText={value => { setQuery(value); setOpponentId(null); setDraftId(randomUUID()); }} style={s.input} autoCorrect={false} />
      {discovery.loading ? <View style={s.state}><ActivityIndicator color={c.darkInk} /></View> : discovery.failed || discovery.refusal ? <View style={s.state}><Text style={s.meta}>{copy('Les crews de ta ville sont indisponibles pour cette recherche.', 'Crews in your city are unavailable for this search.')}</Text><ProfileButton label={copy('Réessayer', 'Try again')} secondary onPress={discovery.reload} /></View> : opponents.length ? opponents.map(item => choice(item.id, item.id === opponentId, item.name, copy(`${item.memberCount} membres`, `${item.memberCount} members`), () => { setOpponentId(item.id); setDraftId(randomUUID()); })) : <Text style={[s.meta, { marginTop: 12 }]}>{copy('Aucun autre crew trouvé dans ta ville.', 'No other crew found in your city.')}</Text>}
      {arena ? <><ProfileSection title={copy('Le départ', 'The start')} />{dates.map(value => choice(value, startsAt === value, datetime(value, arena.timeZone), arena.timeZone, () => { setStartsAt(value); setDraftId(randomUUID()); }))}
        {checkbox(accessConsent, setAccessConsent, copy('Je confirme que les secteurs sont accessibles à mon équipe dans le respect des règles locales.', 'I confirm these sectors are accessible to my team under local rules.'))}
      </> : null}
      <Text style={[s.meta, { marginVertical: 16 }]}>{copy('L’invitation ne remplit aucune équipe. Cinq membres de chaque crew devront s’inscrire volontairement avant le départ.', 'The invitation does not fill either team. Five members of each crew must volunteer before the start.')}</Text>
      <ProfileButton label={copy('Envoyer l’invitation', 'Send invitation')} busy={data.busy} disabled={!direction || !arena || !opponent || !startsAt || !accessConsent} onPress={() => void createMatch()} />
    </> : selected ? <>
      <Text style={[local.label, { marginTop: 12 }]}>{statusLabel(selected)}</Text><Text style={[s.sectionTitle, { marginTop: 8 }]}>{selected.teams.map(team => team.name).join(' / ')}</Text><Text style={[s.meta, { marginTop: 10 }]}>{selected.title} · {selected.activity === 'run' ? copy('Course', 'Run') : copy('Vélo', 'Ride')}</Text><Text style={s.meta}>{datetime(selected.startsAt, selected.timeZone)} → {datetime(selected.endsAt, selected.timeZone)}</Text><Text style={s.meta}>{selected.timeZone}</Text>
      {selected.reason === 'roster_incomplete_at_start' ? <Text style={[s.meta, { marginTop: 12 }]}>{copy('Le défi n’a pas pu démarrer avec deux équipes valides.', 'The challenge could not start with two valid teams.')}</Text> : null}
      <CrewArenaPreview2026 sectors={selected.sectors} />
      <View style={local.teams}>{selected.teams.map(team => <View key={team.id} style={local.team}><Text style={s.linkTitle}>{team.name}{team.id === selected.myTeamId ? copy(' · mon crew', ' · my crew') : ''}</Text><Text style={local.players}>{team.players}<Text style={s.meta}> / {rules.playersPerTeam}</Text></Text><Text style={s.meta}>{team.locked ? copy('Équipe figée', 'Team locked') : team.accepted ? copy('Volontaires', 'Volunteers') : copy('Invitation en attente', 'Invitation pending')}</Text></View>)}</View>
      {(() => { const actions = challengeActions2026(selected, Date.now()); return <>
        {confirm ? <View style={s.state}><Text style={s.body}>{confirmCopy(selected, confirm)}</Text><ProfileButton label={confirm === 'cancel' ? copy('Confirmer l’annulation', 'Confirm cancellation') : copy('Confirmer le retrait', 'Confirm withdrawal')} busy={data.busy} onPress={() => { void mutate(confirm === 'cancel' ? 'cancel_crew_challenge_2026' : typeof confirm === 'object' ? 'withdraw_challenge_activity_2026' : 'join_crew_challenge_2026', typeof confirm === 'object' ? { p_run_id: confirm.runId } : confirm === 'withdraw' ? { p_challenge_id: selected.id, p_consent: false } : { p_challenge_id: selected.id }, copy('Le changement est enregistré.', 'The change is saved.')); }} /><ProfileButton label={copy('Revenir au défi', 'Back to challenge')} secondary disabled={data.busy} onPress={() => setConfirm(null)} /></View> : <>
          {actions.accept ? <View style={s.state}>{checkbox(accessConsent, setAccessConsent, copy('Je confirme l’accès de mon équipe aux secteurs publiés.', 'I confirm my team can access the published sectors.'))}<ProfileButton label={copy('Accepter l’invitation', 'Accept invitation')} disabled={!accessConsent} busy={data.busy} onPress={() => void mutate('accept_crew_challenge_2026', { p_challenge_id: selected.id, p_access_confirmed: true }, copy('Invitation acceptée. Les volontaires peuvent s’inscrire.', 'Invitation accepted. Volunteers can now join.'))} /></View> : null}
          {actions.join ? <View style={s.state}><Text style={s.meta}>{copy('Le défi partage des scores par secteur. Cet écran ne publie ni ta trace GPS ni ta position en direct. Tu peux retirer ton consentement.', 'The challenge shares sector scores. This screen publishes neither your GPS route nor your live position. You can withdraw consent.')}</Text>{checkbox(consent, setConsent, copy('Je choisis de participer au défi et au score de ces secteurs.', 'I choose to participate in the challenge and these sector scores.'))}<ProfileButton label={copy('Je participe', 'Join challenge')} disabled={!consent} busy={data.busy} onPress={() => void mutate('join_crew_challenge_2026', { p_challenge_id: selected.id, p_consent: true }, copy('Tu es inscrit volontairement.', 'You have joined voluntarily.'))} /></View> : null}
          {actions.lock ? <View style={s.state}><Text style={s.meta}>{copy('Les cinq volontaires seront figés pour cette rencontre. Le défi est programmé lorsque les deux équipes sont figées.', 'The five volunteers will be locked for this match. It is scheduled once both teams are locked.')}</Text><ProfileButton label={copy('Figer notre équipe', 'Lock our team')} busy={data.busy} onPress={() => void mutate('lock_crew_challenge_2026', { p_challenge_id: selected.id }, copy('Ton équipe est figée.', 'Your team is locked.'))} /></View> : null}
        </>}
        <ProfileSection title={copy('Notre contribution', 'Our contribution')} />
        {selected.ownScore ? <><Text style={local.points}>{selected.ownScore.totalPoints}<Text style={s.meta}> / {rules.maximumPointsPerTeam} {copy('points', 'points')}</Text></Text>{selected.sectors.map(sector => <View key={sector.id} style={local.scoreRow}><Text style={[s.body, { flex: 1 }]}>{sector.title}</Text><Text style={s.linkTitle}>{selected.ownScore?.sectors[sector.id] ?? '—'}</Text></View>)}</> : <Text style={s.meta}>{copy('Notre score est indisponible.', 'Our score is unavailable.')}</Text>}
        <ProfileSection title={selected.status === 'final' ? copy('Résultat', 'Result') : copy('Photo quotidienne', 'Daily snapshot')} />
        {selected.publishedResult ? <><Text style={s.meta}>{selected.publishedAt ? datetime(selected.publishedAt, selected.timeZone) : ''}{(selected.resultRevision ?? 0) > 1 ? copy(' · résultat corrigé', ' · corrected result') : ''}</Text>{selected.publishedResult.scores.map(score => <View key={score.teamId} style={local.scoreRow}><Text style={[s.body, { flex: 1 }]}>{selected.teams.find(team => team.id === score.teamId)?.name ?? copy('Crew', 'Crew')}</Text><Text style={s.linkTitle}>{score.matchPoints} {copy('points de match', 'match points')}</Text></View>)}{selected.status === 'final' ? <Text style={[s.body, { marginTop: 10 }]}>{selected.publishedResult.isDraw ? copy('Égalité.', 'Draw.') : selected.publishedResult.winnerTeamId ? copy('Victoire de ', 'Winner: ') + (selected.teams.find(team => team.id === selected.publishedResult?.winnerTeamId)?.name ?? '') : copy('Résultat en vérification.', 'Result under review.')}</Text> : null}</> : <Text style={s.meta}>{copy(`La comparaison des crews paraît à ${rules.comparativePublicationLocalHour} h dans le fuseau de l’arène. Aucun score adverse en direct.`, `Crew comparisons are published at ${rules.comparativePublicationLocalHour}:00 in the arena timezone. No live opponent scores.`)}</Text>}
        {selected.publishedResult ? <>
          <Pressable accessibilityRole="button" accessibilityState={{ expanded: scoresExpanded }} onPress={() => setScoresExpanded(value => !value)} style={local.back}><Text style={s.linkAction}>{scoresExpanded ? copy('Masquer les secteurs', 'Hide sectors') : copy('Voir les secteurs publiés', 'View published sectors')}</Text></Pressable>
          {scoresExpanded ? <View>{selected.sectors.map(sector => <View key={sector.id} style={local.publishedSector}><Text style={s.linkTitle}>{sector.title}</Text>{selected.publishedResult!.scores.map(score => <View key={score.teamId} style={local.matchTop}><Text style={[s.meta, { flex: 1 }]}>{selected.teams.find(team => team.id === score.teamId)?.name}</Text><Text style={s.meta}>{score.sectors[sector.id] ?? '—'} {copy('points', 'points')}</Text></View>)}</View>)}</View> : null}
        </> : null}
        <Text style={[s.meta, { marginTop: 14 }]}>{copy(`Les ${rules.maximumContributiveDaysPerPlayer} premières journées admissibles donnent chacune ${rules.pointsPerDay} points par personne. La finale laisse ${rules.finalSyncWindowHours} h aux dernières synchronisations.`, `The first ${rules.maximumContributiveDaysPerPlayer} eligible days each give ${rules.pointsPerDay} points per person. The final allows ${rules.finalSyncWindowHours} hours for late syncs.`)}</Text>
        {actions.chooseSector ? <><ProfileSection title={copy('Mon secteur préféré', 'My preferred sector')} /><Text style={s.meta}>{copy('À choisir avant de partir. Le serveur utilise ta boucle admissible et le choix connu au départ.', 'Choose before heading out. The server uses your eligible loop and the preference known at the start.')}</Text>{selected.sectors.map(sector => choice(sector.id, selected.myPreference?.sectorId === sector.id, sector.title, null, () => { void mutate('set_challenge_preference_2026', { p_challenge_id: selected.id, p_sector_id: sector.id }, copy('Préférence enregistrée pour ta prochaine sortie.', 'Preference saved for your next activity.')); }))}</> : null}
        {selected.myContributions.length ? <><ProfileSection title={copy('Mes journées', 'My days')} />{selected.myContributions.map((contribution, index) => <View key={`${contribution.runId ?? contribution.day}:${index}`} style={local.contribution}><Text style={s.linkTitle}>{contribution.day} · {selected.sectors.find(sector => sector.id === contribution.sectorId)?.title ?? contribution.sectorId}</Text><Text style={s.meta}>{contribution.withdrawn ? copy('Participation retirée', 'Contribution withdrawn') : contribution.points === null ? copy('Points en vérification', 'Points under review') : `${contribution.points} ${copy('points confirmés', 'confirmed points')}`}</Text>{contribution.runId && !contribution.withdrawn ? <Pressable accessibilityRole="button" disabled={data.busy} onPress={() => setConfirm({ runId: contribution.runId! })} style={local.back}><Text style={s.linkAction}>{copy('Retirer cette contribution', 'Withdraw this contribution')}</Text></Pressable> : null}</View>)}</> : null}
        {!confirm ? <View style={s.state}>{actions.withdraw ? <ProfileButton label={copy('Retirer mon consentement', 'Withdraw my consent')} secondary disabled={data.busy} onPress={() => setConfirm('withdraw')} /> : null}{actions.cancel ? <ProfileButton label={copy('Annuler le défi', 'Cancel challenge')} secondary disabled={data.busy} onPress={() => setConfirm('cancel')} /> : null}</View> : null}
      </>; })()}
      <ProfileLink title={copy('Actualiser le résultat', 'Refresh result')} icon="historique" onPress={data.reload} />
    </> : <View style={s.state}><Text style={s.body}>{copy('Ce défi n’est plus accessible à ton compte.', 'This challenge is no longer accessible to your account.')}</Text><ProfileButton label={copy('Revenir à la liste', 'Back to list')} onPress={() => setMode('list')} /></View>}
  </ProfilePage>;
}
const local = StyleSheet.create({ heading: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 20 }, back: { minHeight: 44, justifyContent: 'center' }, match: { paddingVertical: 18, borderBottomWidth: 1, borderColor: c.darkSurfaceMuted, gap: 8 }, matchTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, label: { fontFamily: fonts.textMedium, fontSize: 11, color: c.darkMuted }, matchTitle: { fontFamily: fonts.displayMedium, fontSize: 18, lineHeight: 23, color: c.darkInk }, choice: { paddingVertical: 14, paddingHorizontal: 12, borderWidth: 1, borderColor: c.darkSurfaceMuted, borderRadius: 12, marginTop: 9, flexDirection: 'row', alignItems: 'center', gap: 12 }, chosen: { borderColor: c.accent, backgroundColor: c.darkSurface }, check: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12 }, checkBox: { width: 22, height: 22, borderWidth: 1, borderColor: c.darkMuted, borderRadius: 6, alignItems: 'center', justifyContent: 'center' }, checked: { borderColor: c.accent, backgroundColor: c.accent }, teams: { flexDirection: 'row', gap: 10 }, team: { flex: 1, backgroundColor: c.darkSurface, borderRadius: 14, padding: 13, gap: 10 }, players: { fontFamily: fonts.displayMedium, fontSize: 25, color: c.darkInk }, points: { fontFamily: fonts.displayMedium, fontSize: 30, color: c.darkInk, marginBottom: 10 }, scoreRow: { flexDirection: 'row', gap: 12, alignItems: 'center', paddingVertical: 13, borderBottomWidth: 1, borderColor: c.darkSurfaceMuted }, publishedSector: { paddingVertical: 12, gap: 8, borderBottomWidth: 1, borderColor: c.darkSurfaceMuted }, contribution: { paddingVertical: 12, gap: 7, borderBottomWidth: 1, borderColor: c.darkSurfaceMuted } });
