import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { fonts, refonteColors as c, type Activity } from '@klaim/shared';
import { GrydIcon } from '../../ui/gryd';
import { useLocale } from '../../i18n/store';
import { screen } from '../../lib/analytics';
import { useGrydPlusAccess } from '../premium';
import { activitiesInPeriod2026, comparisonPeriods2026, summarizeComparison2026 } from '../premium/comparison2026';
import { useProfileJournal } from './ProfileJournal';
import { ProfileButton, ProfileLink, ProfilePage, ProfileSegments, s, useRefonteCopy } from './ProfilePrimitives';

export function ProfileComparisonScreen() {
  const copy = useRefonteCopy(); const locale = useLocale(); const access = useGrydPlusAccess();
  const [activity, setActivity] = useState<Activity>('run'); const [mode, setMode] = useState<'activities' | 'periods'>('activities');
  const [days, setDays] = useState<7 | 28>(7); const [picked, setPicked] = useState<[string | null, string | null]>([null, null]);
  const [showMethod, setShowMethod] = useState(false);
  const [picking, setPicking] = useState<0 | 1 | null>(null); const [visible, setVisible] = useState(10);
  const journal = useProfileJournal(activity);
  useEffect(() => { screen('premium-analytics'); }, []);
  const first = journal.runs.find(run => run.id === picked[0]) ?? journal.runs[0];
  const second = journal.runs.find(run => run.id === picked[1] && run.id !== first?.id) ?? journal.runs.find(run => run.id !== first?.id);
  const periods = useMemo(() => comparisonPeriods2026(new Date(), days), [days, journal.runs]);
  const left = summarizeComparison2026(mode === 'activities' ? first ? [first] : [] : activitiesInPeriod2026(journal.runs, periods.current));
  const right = summarizeComparison2026(mode === 'activities' ? second ? [second] : [] : activitiesInPeriod2026(journal.runs, periods.previous));
  const dateLabel = (ms: number) => new Date(ms).toLocaleDateString(locale, { day: 'numeric', month: 'short' });
  const number = (value: number, digits = 1) => value.toLocaleString(locale, { maximumFractionDigits: digits });
  const pace = (value: number | null) => value === null ? '—' : `${Math.floor(Math.round(value) / 60)}:${String(Math.round(value) % 60).padStart(2, '0')}`;
  const rows = [
    { label: copy('Distance', 'Distance'), unit: 'km', a: number(left.km), b: number(right.km) },
    { label: copy('Durée', 'Duration'), unit: 'min', a: number(left.durationS / 60, 0), b: number(right.durationS / 60, 0) },
    { label: activity === 'run' ? copy('Allure moyenne', 'Average pace') : copy('Vitesse moyenne', 'Average speed'), unit: activity === 'run' ? 'min/km' : 'km/h', a: activity === 'run' ? pace(left.paceSPerKm) : left.speedKmh === null ? '—' : number(left.speedKmh), b: activity === 'run' ? pace(right.paceSPerKm) : right.speedKmh === null ? '—' : number(right.speedKmh) },
    ...(mode === 'periods' ? [{ label: copy('Sorties', 'Activities'), unit: '', a: String(left.count), b: String(right.count) }] : []),
  ];
  return <ProfilePage tone="light" title={copy('Comparaisons', 'Comparisons')} back backHref="/premium">
    <Text style={local.accessLabel}>{copy('GRYD+ · Comparaisons privées', 'GRYD+ · Private comparisons')}</Text>
    {access.status === 'loading' ? <View style={local.state}><ActivityIndicator size="small" color={c.ink} /><Text style={local.meta}>{copy('Vérification de ton accès…', 'Checking access…')}</Text></View>
      : access.status === 'unavailable' || access.status === 'pending' ? <View style={local.intro}><View style={local.introMark}><GrydIcon name="clock" size={24} color={c.accent} /></View>
        <Text style={local.introTitle}>{access.status === 'pending' ? copy('Confirmation en cours.', 'Confirming your access.') : copy('Droits non vérifiés.', 'Access not verified.')}</Text>
        <Text style={local.introMeta}>{access.status === 'pending' ? copy('Le Store a enregistré ton achat. Les comparaisons s’ouvriront dès que le droit est confirmé.', 'The Store registered your purchase. Comparisons open as soon as access is confirmed.') : copy('Tes droits GRYD+ n’ont pas pu être lus. Ce n’est pas une réponse : on ne sait pas encore.', 'Your GRYD+ access could not be read. That is not an answer: we do not know yet.')}</Text>
        <View style={local.compactAction}><ProfileButton tone="light" label={copy('Revérifier mes droits', 'Recheck access')} onPress={access.reload} /></View></View>
      : !access.active ? <View style={local.intro}><View style={local.introMark}><GrydIcon name="chart" size={24} color={c.accent} /></View><Text style={local.introTitle}>{copy('Deux sorties, côte à côte.', 'Two activities, side by side.')}</Text><Text style={local.introMeta}>{copy('Distance, durée et allure. Compare deux activités ou deux périodes de ton journal.', 'Distance, duration and pace. Compare two activities or two periods from your journal.')}</Text><View style={local.compactAction}><ProfileButton tone="light" label={copy('Découvrir GRYD+', 'Explore GRYD+')} onPress={() => router.push('/premium')} /></View></View> : <>
      <View style={local.filters}><View style={s.flex}><ProfileSegments tone="light" value={activity} onChange={value => { setActivity(value); setPicked([null, null]); setPicking(null); }} options={[{ key: 'run', label: copy('Course', 'Run') }, { key: 'bike', label: copy('Vélo', 'Ride') }]} /></View><View style={s.flex}><ProfileSegments tone="light" value={mode} onChange={value => { setMode(value); setPicking(null); }} options={[{ key: 'activities', label: copy('Sorties', 'Activities') }, { key: 'periods', label: copy('Périodes', 'Periods') }]} /></View></View>
      {mode === 'periods' ? <View style={local.control}><ProfileSegments tone="light" value={String(days)} onChange={value => setDays(value === '7' ? 7 : 28)} options={[{ key: '7', label: copy('7 jours', '7 days') }, { key: '28', label: copy('28 jours', '28 days') }]} /></View> : null}
      {journal.status === 'loading' ? <View style={local.state}><ActivityIndicator size="small" color={c.ink} /></View> : journal.status === 'failed' ? <View style={local.empty}><Text style={local.meta}>{copy('Tes activités n’ont pas pu être chargées.', 'Your activities could not be loaded.')}</Text><ProfileButton tone="light" label={copy('Réessayer', 'Try again')} secondary onPress={journal.reload} /></View> : mode === 'activities' && (!first || !second) ? <View style={local.empty}><Text style={local.meta}>{copy('Il faut deux sorties dans cette discipline pour les comparer.', 'Record two activities in this sport to compare them.')}</Text><ProfileButton tone="light" label={copy('Ouvrir la carte', 'Open map')} onPress={() => router.push('/(tabs)')} /></View> : <>
        <View style={local.columns}>{([0, 1] as const).map(side => <Pressable key={side} accessibilityRole={mode === 'activities' ? 'button' : undefined} disabled={mode !== 'activities'} aria-disabled={mode !== 'activities'} accessibilityState={{ disabled: mode !== 'activities', expanded: mode === 'activities' ? picking === side : undefined }} aria-expanded={mode === 'activities' ? picking === side : undefined} onPress={() => setPicking(picking === side ? null : side)} style={[local.columnHead, side === 0 && local.currentHead]}><View style={local.columnTop}><Text style={local.sideLetter}>{side === 0 ? 'A' : 'B'}</Text>{mode === 'activities' ? <GrydIcon name="chevronDown" size={18} color={c.muted} /> : null}</View><Text style={local.columnLabel}>{mode === 'activities' ? copy(`Sortie ${side === 0 ? 'A' : 'B'}`, `Activity ${side === 0 ? 'A' : 'B'}`) : side === 0 ? copy('Période récente', 'Recent period') : copy('Période précédente', 'Previous period')}</Text><Text style={local.date}>{mode === 'activities' ? dateLabel((side === 0 ? first : second)!.startedAtMs) : `${dateLabel((side === 0 ? periods.current : periods.previous).start)} – ${dateLabel((side === 0 ? periods.current : periods.previous).end - 1)}`}</Text>{mode === 'activities' ? <Text style={local.edit}>{copy('Changer', 'Change')}</Text> : null}</Pressable>)}</View>
        {picking !== null ? <View style={local.picker}><Text style={local.meta}>{copy('Choisir une sortie', 'Choose an activity')}</Text>{journal.runs.slice(0, visible).map(run => { const other = picking === 0 ? second : first; return <Pressable key={run.id} disabled={run.id === other?.id} aria-disabled={run.id === other?.id} accessibilityState={{ disabled: run.id === other?.id }} accessibilityRole="button" onPress={() => { setPicked(picking === 0 ? [run.id, second?.id ?? null] : [first?.id ?? null, run.id]); setPicking(null); }} style={[local.choice, run.id === other?.id && s.disabled]}><Text style={local.body}>{dateLabel(run.startedAtMs)} · {number(run.km)} km</Text><Text style={local.meta}>{Math.round(run.durationS / 60)} min</Text></Pressable>; })}{journal.runs.length > visible ? <ProfileButton tone="light" label={copy('Plus de sorties', 'More activities')} secondary onPress={() => setVisible(value => value + 10)} /> : null}</View> : null}
        {rows.map((row, index) => <View key={row.label} style={[local.metric, index === 0 && local.primaryMetric]}>
          <Text style={[local.meta, index === 0 && local.primaryMeta]}>{row.label} {row.unit ? `· ${row.unit}` : ''}</Text>
          <View style={local.metricValues}><Text adjustsFontSizeToFit minimumFontScale={0.6} numberOfLines={1} accessibilityLabel={`A : ${row.a} ${row.unit}`} style={[local.value, index === 0 && local.primaryValue]}>{row.a}</Text><Text adjustsFontSizeToFit minimumFontScale={0.6} numberOfLines={1} accessibilityLabel={`B : ${row.b} ${row.unit}`} style={[local.value, index === 0 && local.primaryValue]}>{row.b}</Text></View>
          {index === 0 && (left.km > 0 || right.km > 0) ? <View style={local.comparisonBars} accessible accessibilityLabel={copy(`Distance A : ${row.a} km. Distance B : ${row.b} km.`, `Distance A: ${row.a} km. Distance B: ${row.b} km.`)}>{[left.km, right.km].map((distance, side) => <View key={side} style={local.comparisonBarRow}><Text style={local.barLabel}>{side === 0 ? 'A' : 'B'}</Text><View style={local.barTrack}><View style={[local.bar, { width: `${distance / Math.max(left.km, right.km) * 100}%`, backgroundColor: side === 0 ? c.accent : c.darkMuted }]} /></View></View>)}</View> : null}
        </View>)}
        <Pressable accessibilityRole="button" accessibilityState={{ expanded: showMethod }} aria-expanded={showMethod} onPress={() => setShowMethod(value => !value)} style={local.disclosure}><Text style={local.linkText}>{copy('Méthode de calcul', 'Calculation method')}</Text><GrydIcon name={showMethod ? 'minus' : 'plus'} size={18} color={c.muted} /></Pressable>
        {showMethod ? <Text style={local.notice}>{copy('Calculé sur les sorties disponibles dans ton journal récent. Les allures et vitesses utilisent la durée enregistrée, pauses comprises si elles n’ont pas été déduites à la source.', 'Calculated from activities available in your recent journal. Pace and speed use recorded duration, including pauses when the source has not removed them.')}</Text> : null}
        {left.pending || right.pending ? <Text style={local.notice}>{copy('Inclut des activités locales en attente de synchronisation.', 'Includes local activities awaiting sync.')}</Text> : null}
        {journal.historyStatus !== 'ready' ? <Text style={local.notice}>{copy('Historique serveur indisponible : seules les sorties de cet appareil sont incluses.', 'Server history unavailable: only activities on this device are included.')}</Text> : null}
      </>}
    </>}
    <View style={local.links}><ProfileLink tone="light" title={copy('Mes statistiques', 'My statistics')} subtitle={copy('Incluses gratuitement', 'Included for free')} icon="performance" onPress={() => router.push('/performance')} /></View>
  </ProfilePage>;
}
const local = StyleSheet.create({
  accessLabel: { fontFamily: fonts.text, fontSize: 13, lineHeight: 19, color: c.muted, paddingBottom: 16 }, filters: { gap: 8, marginBottom: 12 }, control: { marginBottom: 12 }, meta: { fontFamily: fonts.text, fontSize: 13, lineHeight: 19, color: c.muted }, body: { fontFamily: fonts.text, fontSize: 14, lineHeight: 21, color: c.ink }, intro: { backgroundColor: c.carbon, borderRadius: 24, padding: 24, gap: 14 }, introMark: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: c.darkSurfaceMuted, marginBottom: 8 }, introTitle: { fontFamily: fonts.displayMedium, fontSize: 28, lineHeight: 35, letterSpacing: -.7, color: c.darkInk }, introMeta: { fontFamily: fonts.text, fontSize: 14, lineHeight: 21, color: c.darkMuted }, empty: { padding: 20, backgroundColor: c.surface, borderRadius: 24, gap: 12, marginBottom: 12 }, compactAction: { alignSelf: 'flex-start', marginTop: 4 }, state: { padding: 22, borderRadius: 24, backgroundColor: c.surface, gap: 10, flexDirection: 'row', alignItems: 'center' },
  columns: { flexDirection: 'row', gap: 12, marginBottom: 12 }, columnHead: { flex: 1, padding: 18, borderRadius: 24, backgroundColor: c.surface, borderWidth: 1, borderColor: c.surface, gap: 6, minHeight: 128 }, currentHead: { borderColor: c.border }, columnTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }, sideLetter: { fontFamily: fonts.textSemi, fontSize: 13, color: c.ink }, columnLabel: { color: c.muted, fontFamily: fonts.text, fontSize: 12, lineHeight: 18 }, date: { color: c.ink, fontFamily: fonts.textMedium, fontSize: 15, lineHeight: 21 }, edit: { color: c.muted, fontFamily: fonts.text, fontSize: 12, lineHeight: 18, marginTop: 4 }, picker: { marginBottom: 12, padding: 20, backgroundColor: c.surface, borderRadius: 24 }, choice: { minHeight: 48, paddingVertical: 12, flexDirection: 'row', justifyContent: 'space-between', gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: c.border }, metric: { padding: 20, backgroundColor: c.surface, borderRadius: 24, marginBottom: 12, gap: 10 }, primaryMetric: { backgroundColor: c.carbon, padding: 22 }, primaryMeta: { color: c.darkMuted }, metricValues: { flexDirection: 'row', gap: 20 }, value: { flex: 1, fontFamily: fonts.displayMedium, fontSize: 28, lineHeight: 36, color: c.ink, fontVariant: ['tabular-nums'] }, primaryValue: { fontSize: 36, lineHeight: 44, color: c.darkInk }, comparisonBars: { gap: 12, marginTop: 12 }, comparisonBarRow: { flexDirection: 'row', gap: 12, alignItems: 'center' }, barLabel: { width: 12, fontFamily: fonts.textMedium, fontSize: 11, color: c.darkMuted }, barTrack: { flex: 1, height: 12, borderRadius: 6, backgroundColor: c.darkSurface }, bar: { height: 12, borderRadius: 6 }, disclosure: { minHeight: 48, flexWrap: 'wrap', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, linkText: { fontFamily: fonts.textMedium, fontSize: 13, color: c.ink }, notice: { fontFamily: fonts.text, fontSize: 13, lineHeight: 19, color: c.muted, marginTop: 10 }, links: { marginTop: 16 },
});
