/**
 * GRYD — i18n : labels a11y (VoiceOver) des APERÇUS de l'Arsenal.
 *
 * Les composants de preview (features/arsenal/preview/mechanics.tsx & cosmetic.tsx)
 * décrivaient l'objet à VoiceOver en français dur. Ici les mêmes phrases, 5 langues,
 * résolues au rendu. {name} = le nom de l'item (arsenalName), {hours} = durée bouclier.
 */
import type { Entry } from '../types';

export const ARSENAL_PREVIEW_I18N = {
  'preview.cosmetic.banner': { fr: 'Aperçu de la bannière crew : {name}. Style visuel uniquement, aucun effet de jeu.', en: 'Preview of the Crew banner: {name}. Visual style only, no gameplay effect.', es: 'Vista previa de la bandera del Crew: {name}. Solo estilo visual, sin ningún efecto de juego.', de: 'Vorschau des Crew-Banners: {name}. Nur visueller Stil, keine Spielwirkung.', pt: 'Pré-visualização da bandeira do Crew: {name}. Apenas estilo visual, sem nenhum efeito de jogo.' },
  'preview.cosmetic.emblem': { fr: 'Aperçu du blason crew : {name}. Style visuel uniquement, aucun effet de jeu.', en: 'Preview of the Crew emblem: {name}. Visual style only, no gameplay effect.', es: 'Vista previa del blasón del Crew: {name}. Solo estilo visual, sin ningún efecto de juego.', de: 'Vorschau des Crew-Wappens: {name}. Nur visueller Stil, keine Spielwirkung.', pt: 'Pré-visualização do brasão do Crew: {name}. Apenas estilo visual, sem nenhum efeito de jogo.' },
  'preview.cosmetic.frame': { fr: 'Aperçu du cadre de profil : {name}. Style visuel uniquement, aucun effet de jeu.', en: 'Preview of the profile frame: {name}. Visual style only, no gameplay effect.', es: 'Vista previa del marco de perfil: {name}. Solo estilo visual, sin ningún efecto de juego.', de: 'Vorschau des Profilrahmens: {name}. Nur visueller Stil, keine Spielwirkung.', pt: 'Pré-visualização da moldura de perfil: {name}. Apenas estilo visual, sem nenhum efeito de jogo.' },
  'preview.cosmetic.skinTerritory': { fr: 'Aperçu du skin de territoire : {name}. Style visuel uniquement, aucun effet de jeu.', en: 'Preview of the territory skin: {name}. Visual style only, no gameplay effect.', es: 'Vista previa del skin de territorio: {name}. Solo estilo visual, sin ningún efecto de juego.', de: 'Vorschau des Territorium-Skins: {name}. Nur visueller Stil, keine Spielwirkung.', pt: 'Pré-visualização do skin de território: {name}. Apenas estilo visual, sem nenhum efeito de jogo.' },
  'preview.cosmetic.skinTrace': { fr: 'Aperçu du skin de trace : {name}. Style visuel uniquement, aucun effet de jeu.', en: 'Preview of the trace skin: {name}. Visual style only, no gameplay effect.', es: 'Vista previa del skin de trazado: {name}. Solo estilo visual, sin ningún efecto de juego.', de: 'Vorschau des Spur-Skins: {name}. Nur visueller Stil, keine Spielwirkung.', pt: 'Pré-visualização do skin de traçado: {name}. Apenas estilo visual, sem nenhum efeito de jogo.' },
  'preview.cosmetic.template': { fr: 'Aperçu de la share card : {name}. Style visuel uniquement, aucun effet de jeu.', en: 'Preview of the share card: {name}. Visual style only, no gameplay effect.', es: 'Vista previa de la share card: {name}. Solo estilo visual, sin ningún efecto de juego.', de: 'Vorschau der Share Card: {name}. Nur visueller Stil, keine Spielwirkung.', pt: 'Pré-visualização da share card: {name}. Apenas estilo visual, sem nenhum efeito de jogo.' },
  'preview.mechanics.club': { fr: '{name} : stats, heatmap, export HD et templates premium — zéro avantage de jeu, aucun bouclier, aucune info tactique.', en: '{name}: stats, heatmap, HD export and premium templates — zero gameplay advantage, no shield, no tactical intel.', es: '{name}: estadísticas, heatmap, exportación HD y templates premium — cero ventaja de juego, ningún escudo, ninguna información táctica.', de: '{name}: Statistiken, Heatmap, HD-Export und Premium-Templates — null Spielvorteil, kein Schild, keine taktischen Infos.', pt: '{name}: estatísticas, heatmap, exportação HD e templates premium — zero vantagem de jogo, nenhum escudo, nenhuma informação tática.' },
  'preview.mechanics.crewBoost': { fr: '{name} : +25 % de progression du coffre crew — jamais de points ni de zones.', en: '{name}: +25% Crew chest progress — never points or zones.', es: '{name}: +25 % de progreso del cofre del Crew — nunca puntos ni zonas.', de: '{name}: +25 % Fortschritt der Crew-Truhe — niemals Punkte oder Zonen.', pt: '{name}: +25 % de progresso do baú do Crew — nunca pontos nem zonas.' },
  'preview.mechanics.eclats': { fr: '{name} : des Éclats — la monnaie du style (skins, frames, templates), jamais du territoire.', en: '{name}: Éclats — the currency of style (skins, frames, templates), never of territory.', es: '{name}: Éclats — la moneda del estilo (skins, frames, templates), nunca del territorio.', de: '{name}: Éclats — die Währung für Stil (Skins, Frames, Templates), niemals für Territorium.', pt: '{name}: Éclats — a moeda do estilo (skins, frames, templates), nunca do território.' },
  'preview.mechanics.pack': { fr: '{name} : un bundle qui livre plusieurs cosmétiques d\'un coup — du style, aucun avantage de jeu.', en: '{name}: a bundle that delivers several cosmetics at once — style, no gameplay advantage.', es: '{name}: un pack que entrega varios cosméticos de una vez — estilo, ninguna ventaja de juego.', de: '{name}: ein Bundle, das mehrere Kosmetika auf einmal liefert — Stil, kein Spielvorteil.', pt: '{name}: um pacote que entrega vários cosméticos de uma vez — estilo, nenhuma vantagem de jogo.' },
  'preview.mechanics.pass': { fr: '{name} : 30 niveaux de récompenses de saison — pas encore lancé (bientôt).', en: '{name}: 30 levels of season rewards — not launched yet (soon).', es: '{name}: 30 niveles de recompensas de temporada — aún no disponible (pronto).', de: '{name}: 30 Stufen an Saisonbelohnungen — noch nicht gestartet (bald).', pt: '{name}: 30 níveis de recompensas de temporada — ainda não lançado (em breve).' },
  'preview.mechanics.scoutPing': { fr: '{name} : un ping révèle une zone fragile ou rentable — une info, aucune capture automatique.', en: '{name}: a ping reveals a fragile or profitable zone — information only, no automatic capture.', es: '{name}: un ping revela una zona frágil o rentable — solo información, ninguna captura automática.', de: '{name}: Ein Ping enthüllt eine schwache oder lohnende Zone — eine Information, keine automatische Einnahme.', pt: '{name}: um ping revela uma zona frágil ou rentável — apenas informação, nenhuma captura automática.' },
  'preview.mechanics.shield': { fr: '{name} : protège une zone pendant {hours} h, sans la rendre invincible.', en: '{name}: protects a zone for {hours} h without making it invincible.', es: '{name}: protege una zona durante {hours} h, sin volverla invencible.', de: '{name}: schützt eine Zone für {hours} h, ohne sie unverwundbar zu machen.', pt: '{name}: protege uma zona durante {hours} h, sem torná-la invencível.' },
  'preview.mechanics.streakGel': { fr: '{name} : gèle et protège ta série hebdo une semaine — et donc le multiplicateur de points qu\'elle porte. Ne capture aucune zone, ne se vend jamais.', en: '{name}: freezes and protects your weekly streak for one week — and with it the points multiplier it carries. Captures no zone, never for sale.', es: '{name}: congela y protege tu racha semanal durante una semana — y con ella el multiplicador de puntos que conlleva. No captura ninguna zona, nunca se vende.', de: '{name}: friert deine Wochen-Serie eine Woche lang ein und schützt sie — und damit den Punktemultiplikator, den sie trägt. Nimmt keine Zone ein, wird nie verkauft.', pt: '{name}: congela e protege a tua sequência semanal durante uma semana — e com ela o multiplicador de pontos que carrega. Não captura nenhuma zona, nunca é vendida.' },
} satisfies Record<string, Entry>;
